/* Generated by generate_tests.py */
/* Do not modify */

#if defined(TORCHAO_ENABLE_KLEIDI)

/*****************/
// dotprod_1x4x32 tests 
/*****************/


TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn4xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m1xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m2xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m2xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m3xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m4xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/4, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m3xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m31xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/31, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m32xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/32, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m33xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/33, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m34xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/34, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m35xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/35, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m7xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m17xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m23xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m41xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m7xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m17xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m23xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m41xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m19xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/19, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m23xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m29xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/29, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x4x32_m101xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/101, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}




/*****************/
// dotprod_1x8x32 tests 
/*****************/


TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn4xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m1xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m2xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m2xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m3xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m4xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/4, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m3xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m31xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/31, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m32xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/32, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m33xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/33, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m34xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/34, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m35xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/35, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m7xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m17xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m23xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m41xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m7xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m17xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m23xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m41xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m19xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/19, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m23xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m29xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/29, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_dotprod_1x8x32_m101xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<dotprod_1x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/101, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}




/*****************/
// i8mm_4x8x32 tests 
/*****************/
#if defined(TORCHAO_ENABLE_ARM_I8MM)

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn4xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m1xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m2xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m2xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m3xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m4xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/4, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m3xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m31xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/31, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m32xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/32, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m33xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/33, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m34xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/34, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m35xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/35, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m7xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m17xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m23xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m41xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m7xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m17xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m23xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m41xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m19xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/19, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m23xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m29xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/29, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_4x8x32_m101xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_4x8x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/101, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

#endif // TORCHAO_ENABLE_ARM_I8MM


/*****************/
// i8mm_8x4x32 tests 
/*****************/
#if defined(TORCHAO_ENABLE_ARM_I8MM)

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn4xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m1xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/1, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m2xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m2xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/2, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m3xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m4xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/4, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m3xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/3, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m31xn2xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/31, /*n=*/2, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m32xn4xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/32, /*n=*/4, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m33xn6xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/33, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m34xn8xk32xg32_bias_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/34, /*n=*/8, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m35xn6xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/35, /*n=*/6, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m7xn22xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/22, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m17xn26xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/26, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m23xn102xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/102, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m41xn222xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/222, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m7xn11xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/7, /*n=*/11, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m17xn13xk32xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/17, /*n=*/13, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m23xn51xk32xg32_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/51, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m41xn111xk32xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/41, /*n=*/111, /*k=*/32, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m19xn14xk64xg32) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/19, /*n=*/14, /*k=*/64, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m23xn22xk128xg32_bias) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      true /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/23, /*n=*/22, /*k=*/128, /*group_size=*/32, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m29xn26xk64xg64_clamp) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      true /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/29, /*n=*/26, /*k=*/64, /*group_size=*/64, &ukernel_config);
}

TEST(test_linear_8bit_act_xbit_weight, Kleidi_i8mm_8x4x32_m101xn34xk128xg64) {
  UKernelConfig ukernel_config = get_ukernel_config_kleidi<i8mm_8x4x32>();
  test_linear_8bit_act_xbit_weight<
      4 /*weight_nbit*/,
      false /*has_weight_zeros*/,
      false /*has_bias*/,
      false /*has_clamp*/,
      true /*has_kleidi*/>(
      /*m=*/101, /*n=*/34, /*k=*/128, /*group_size=*/64, &ukernel_config);
}

#endif // TORCHAO_ENABLE_ARM_I8MM

#endif // TORCHAO_ENABLE_KLEIDI
