# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

# =============================================================
#  This script automatically cleans up the raw release notes
#  generated by github by doing an initial pass to sort the
#  commits by module. The output still requires manual reviewing.
#
#  This script uses PyGithub. If you don't have it yet, please
#  install it using:
#
#    pip install PyGithub
#
#  We expect the following format for the input release notes:
#
#    ## What's Changed
#    * commit1_title by @userX in https://github.com/pytorch/ao/pull/123
#    * commit2_title by @userY in https://github.com/pytorch/ao/pull/234
#    * commit3_title by @userZ in https://github.com/pytorch/ao/pull/345
#
#    ## New Contributors
#    * @userX made their first contribution in https://github.com/pytorch/ao/pull/123
#    * @userY made their first contribution in https://github.com/pytorch/ao/pull/234
#
#  Example output:
#
#    ## Highlights
#
#    We are excited to announce the X.Y.Z release of torchao!
#
#    ### Highlight Feature 1
#
#    ### Highlight Feature 2
#
#    ## BC Breaking
#
#    ## Deprecations
#
#    ## quantization
#    * commit1_title (https://github.com/pytorch/ao/pull/123)
#
#    ## float8
#    * commit2_title (https://github.com/pytorch/ao/pull/234)
#
#    ## sparsity
#    * commit3_title (https://github.com/pytorch/ao/pull/345)
#
#    ## Not User Facing
#
#    ## New Contributors
#    * @userX made their first contribution in https://github.com/pytorch/ao/pull/123
#    * @userY made their first contribution in https://github.com/pytorch/ao/pull/234
#
# =============================================================


import os
import re
import sys
from collections import OrderedDict
from typing import Dict, List, Set

try:
    from github import Github
except ImportError as err:
    raise ValueError(
        "PyGithub not installed, please run 'pip install PyGithub'"
    ) from err

if len(sys.argv) != 2:
    print("Usage: python clean_release_notes.py [raw_release_notes.txt]")
    sys.exit(1)

input_file = sys.argv[1]
output_file = input_file + ".out"
VERBOSE = os.getenv("VERBOSE", "true").lower() == "true"

# Special module labels that get their own fixed sections
SPECIAL_MODULES = OrderedDict(
    [
        ("module: bc-breaking", "BC Breaking"),
        ("module: deprecation", "Deprecations"),
        ("module: not user facing", "Not User Facing"),
    ]
)


def clean_release_notes():
    """
    Main entry point for this script.

    This function pre-processes the raw release notes and produces a template
    with all the standard sections and pre-sorts the commits into different
    module categories based on github labels.
    """

    # Write the header section
    with open(output_file, "w") as out_f:
        out_f.write("## Highlights\n\n")
        out_f.write("We are excited to announce the X.Y.Z release of torchao!\n\n")
        out_f.write("### Highlight Feature 1\n\n")
        out_f.write("### Highlight Feature 2\n\n")

    # Sort commits into different categories and write them to output file
    # For lines after the commits, just copy them to the output file as is
    commit_lines = []
    commit_start = False
    with open(input_file, "r") as in_f, open(output_file, "a") as out_f:
        for line in in_f.readlines():
            if line.startswith("## What's Changed"):
                commit_start = True
            elif commit_start and line.startswith("*"):
                commit_lines.append(line)
            elif commit_start:
                # End of commits, fetch PR labels based on commits collected so far
                commit_start = False
                pr_number_to_labels = fetch_pr_labels(commit_lines)

                # Discover all module labels and build categories
                commits_by_category = build_module_categories(
                    commit_lines, pr_number_to_labels
                )

                # Write all commits to the output file by category
                for category, commits in commits_by_category.items():
                    out_f.write("## %s\n\n" % category)
                    for commit_line in commits:
                        out_f.write(format_commit(commit_line))
                    out_f.write("\n")
            else:
                # Not a commit, just copy to the output file
                out_f.write(line)
    print("Wrote to %s." % output_file)


def parse_pr_number(commit_line: str) -> int:
    """
    Helper function to parse PR number from commit line.
    """
    return int(re.match(".*pytorch/ao/pull/(.*)", commit_line).groups()[0])


def fetch_pr_labels(commit_lines: List[str]) -> Dict[int, List[str]]:
    """
    Fetch the relevant github labels starting with "module: " from all PRs.
    Returns a dict mapping PR number to list of module labels.
    """
    pr_number_to_labels: Dict[int, List[str]] = {}
    all_pr_numbers = [parse_pr_number(line) for line in commit_lines]
    smallest_pr_number = min(all_pr_numbers)
    repo = Github().get_repo("pytorch/ao")

    # This call fetches 30 PRs at a time in descending order of when the PR was created
    pulls = repo.get_pulls(state="closed")
    for pr in pulls:
        if pr.number < smallest_pr_number:
            break
        labels = [l.name for l in pr.labels if l.name.startswith("module: ")]
        if len(labels) > 0:
            if VERBOSE:
                print("Found labels for PR %s: %s" % (pr.number, labels))
            pr_number_to_labels[pr.number] = labels
    return pr_number_to_labels


def build_module_categories(
    commit_lines: List[str],
    pr_number_to_labels: Dict[int, List[str]],
) -> OrderedDict:
    """
    Build an ordered dict of category -> list of commit lines.

    Order: special sections (BC Breaking, Deprecations) first,
    then discovered module sections sorted alphabetically,
    then Not User Facing and Uncategorized last.
    """
    # Collect all unique non-special module labels
    module_labels: Set[str] = set()
    for labels in pr_number_to_labels.values():
        for label in labels:
            if label not in SPECIAL_MODULES:
                module_labels.add(label)

    # Build ordered categories: special first, then modules alphabetically
    commits_by_category: OrderedDict = OrderedDict()

    # Add special sections (except "Not User Facing" which goes at the end)
    for label, display_name in SPECIAL_MODULES.items():
        if label != "module: not user facing":
            commits_by_category[display_name] = []

    # Add module sections sorted alphabetically by display name
    sorted_modules = sorted(module_labels, key=lambda l: module_label_to_display(l))
    for label in sorted_modules:
        commits_by_category[module_label_to_display(label)] = []

    # Add "Not User Facing" and "Uncategorized" at the end
    commits_by_category["Not User Facing"] = []
    commits_by_category["Uncategorized"] = []

    # Assign each commit to categories
    for commit_line in commit_lines:
        pr_number = parse_pr_number(commit_line)
        labels = pr_number_to_labels.get(pr_number, [])

        if not labels:
            commits_by_category["Uncategorized"].append(commit_line)
            continue

        for label in labels:
            if label in SPECIAL_MODULES:
                display_name = SPECIAL_MODULES[label]
            else:
                display_name = module_label_to_display(label)
            commits_by_category[display_name].append(commit_line)

    return commits_by_category


def module_label_to_display(label: str) -> str:
    """
    Convert a module label to a display name.
    e.g. "module: quantization" -> "quantization"
    """
    return label.removeprefix("module: ")


def format_commit(commit_line: str) -> str:
    """
    Format the commit line as follows:
      Before: * commit title by @userX in https://github.com/pytorch/ao/pull/123
      After:  * Commit title (https://github.com/pytorch/ao/pull/123)
    """
    # Remove author, put PR link in parentheses
    commit_line = re.sub(" by @.* in (.*)", r" (\g<1>)", commit_line)
    # Capitalize first letter
    commit_line = commit_line.lstrip("* ")
    commit_line = "* " + commit_line[0].upper() + commit_line[1:]
    return commit_line


if __name__ == "__main__":
    clean_release_notes()
