name: Build M1 Wheels
on:
  pull_request:
    paths:
      - build/packaging/**
      - .github/workflows/build_wheels_m1.yml
      - setup.py
  push:
    branches:
      - nightly
      - main
      - release/*
    tags:
        # NOTE: Binary build pipelines should only get triggered on release candidate builds
        # Release candidate tags look like: v1.11.0-rc1
        - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: macos-arm64
  build:
    needs: generate-matrix
    if: github.repository_owner == 'pytorch'
    name: pytorch/ao
    uses: pytorch/test-infra/.github/workflows/build_wheels_macos.yml@main
    with:
      repository: pytorch/ao
      ref: ${{ github.head_ref || github.ref_name }}
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: packaging/pre_build_script.sh
      # post-script: packaging/post_build_script.sh
      package-name: torchao
      runner-type: macos-m1-stable
      smoke-test-script: test/smoke_test.py
      trigger-event: ${{ github.event_name }}
  notify:
    runs-on: ubuntu-latest
    name: Email notification
    needs: [generate-matrix, build]
    if: failure() && github.event_name == 'schedule'
    steps:
      - uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: torchao.notify
          password: ${{ secrets.TORCHAO_NOTIFY_PASSWORD }}
          from: torchao.notify@gmail.com
          to: ${{ secrets.TORCHAO_NOTIFY_RECIPIENT }}
          subject: Scheduled Build Failure for TorchAO
          body: |
            Build Failure Notification for TorchAO
            A failure occurred in the Build Linux Wheels workflow.
            Run Details:
            - Workflow: ${{ github.workflow }}
            - Run Type: ${{ github.event_name }}
            - Repository: ${{ github.repository }}
            - Branch/PR: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            You can view the full run details here:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Error Information:
            ${{ needs.generate-matrix.result == 'failure' && 'Matrix generation failed' || '' }}
            ${{ needs.build.result == 'failure' && 'Build job failed' || '' }}
            
            This is an automated notification. Please check the GitHub Actions page for more details about the failure.
