name: Run Float8nocompile Tests

on:
  push:
    branches:
      - main
      - 'gh/**'
    paths:
      - 'torchao/prototype/float8nocompile/**'
  pull_request:
    branches:
      - main
      - 'gh/**'
    paths:
      - 'torchao/prototype/float8nocompile/**'

concurrency:
  group: floatnocompile_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

# jobs:
#   test:
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - name: H100
#             runs-on: linux.aws.h100
#             torch-spec: '--pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124'
#             gpu-arch-type: "cuda"
#             gpu-arch-version: "12.4"

#     uses: pytorch/test-infra/.github/workflows/linux_job_v2.yml@main
#     with:
#       timeout: 300
#       runner: ${{ matrix.runs-on }}
#       gpu-arch-type: ${{ matrix.gpu-arch-type }}
#       gpu-arch-version: ${{ matrix.gpu-arch-version }}
#       submodules: recursive
#       script: |
#         conda create -n venv python=3.9 -y
#         conda activate venv
#         export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
#         python -m pip install --upgrade pip
#         pip install ${{ matrix.torch-spec }}
#         pip install -r dev-requirements.txt
#         pip install .
#         cd torchao/prototype/float8nocompile
#         pytest kernels/ --verbose -s
#         pytest test/train_test.py --verbose -s
