name: Run Regression Tests on ROCm

on:
  push:
    branches:
      - main
    tags:
      - ciflow/rocm/*

concurrency:
  group: regression_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  test-nightly:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ROCM Nightly
            runs-on: linux.rocm.gpu.gfx942.1
            torch-spec: '--pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm7.0'
            gpu-arch-type: "rocm"
            gpu-arch-version: "7.0"
            docker-image: pytorch/manylinux2_28-builder:rocm7.0

    permissions:
      id-token: write
      contents: read
    uses: pytorch/test-infra/.github/workflows/linux_job_v2.yml@main
    with:
      timeout: 210
      no-sudo: ${{ matrix.gpu-arch-type == 'rocm' }}
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      docker-image: ${{ matrix.docker-image }}
      submodules: recursive
      script: |
        conda create -n venv python=3.10 -y
        conda activate venv
        python -m pip install --upgrade pip
        pip install ${{ matrix.torch-spec }}
        pip install -r dev-requirements.txt
        pip install . --no-build-isolation
        export CONDA=$(dirname $(dirname $(which conda)))
        export LD_LIBRARY_PATH=$CONDA/lib/:$LD_LIBRARY_PATH
        pytest \
          test/test_utils.py \
          test/test_low_bit_optim.py \
          test/dtypes/test_nf4.py \
          test/float8/test_base.py \
          test/float8/test_float8_utils.py \
          test/float8/test_numerics_integration.py \
          test/integration/test_integration.py \
          test/prototype/test_smoothquant.py \
          test/prototype/blockwise_fp8_training/ \
          test/prototype/moe_training/test_kernels.py \
          test/prototype/moe_training/test_mxfp8_grouped_mm.py \
          test/prototype/mx_formats/test_mx_tensor.py \
          test/prototype/mx_formats/test_mx_mm.py \
          test/prototype/mx_formats/test_inference_workflow.py \
          test/prototype/mx_formats/test_nvfp4_tensor.py \
          test/quantization/test_observer.py \
          test/quantization/test_qat.py \
          test/quantization/test_quant_api.py \
          test/quantization/test_quant_primitives.py \
          test/quantization/quantize_/workflows/float8/test_float8_tensor.py \
          test/quantization/quantize_/workflows/int4/test_int4_tile_packed_to_4d_tensor.py \
          --verbose -s
