name: Code Analysis with Ruff

on:
  push:
    branches:
      - main
      - 'gh/**'
  pull_request:
    branches:
      - main
      - 'gh/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.6.8
    - name: Analyzing the code with ruff
      run: |
        ruff check .
    - name: Check *all* Python files for F821, F823, and W191
      run: |
        # --isolated is used to skip the allowlist at all so this applies to all files
        # please be careful when using this large changes means everyone needs to rebase
        ruff check --isolated --select F821,F823,W191
    - name: Check the allow-listed files for F,I
      run: |
        ruff check --select F,I
    - name: Check the allow-listed files for well formatted code
      run: |
        ruff format --check
