name: Code Analysis with Ruff

on:
  push:
    branches:
      - main
      - 'gh/**'
  pull_request:
    branches:
      - main
      - 'gh/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Analyzing the code with ruff
      run: |
        ruff check .
    - name: Check all Python files for syntax errors (E999) and undefined vars (F821)
      run: |
        ruff check --isolated --select E999,F821
    - name: Check well formatted code
      run: |
        ruff format --check
